[project]
name = "first-program"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.115.4",
    "ruff>=0.7.2",
    "sqlalchemy>=2.0.36",
]
